name: Hello DevOps

on:
  push:

  schedule:
    - cron: '0 9 * * 1'   # Every Monday at 9:00 AM UTC

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello DevOps"

      - name: Show Date
        run: date
